### ISSUE TITLE
[BUG]  Getting UnboundLocalError: local variable 'seq_length' referenced before assignment error from Albert

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/Transformers4Rec#297]
### Bug description
I get the following error when training Albert 

```
[INFO|trainer.py:1176] 2021-10-19 20:38:57,691 >>   Total optimization steps = 4500
  0%|                                                                                                                                                               | 0/4500 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/Transformers4Rec/examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py", line 394, in <module>
    main()
  File "/workspace/Transformers4Rec/examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py", line 163, in main
    results_over_time = incremental_train_eval(
  File "/workspace/Transformers4Rec/examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py", line 233, in incremental_train_eval
    trainer.train()
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1286, in train
    tr_loss += self.training_step(model, inputs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1777, in training_step
    loss = self.compute_loss(model, inputs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1811, in compute_loss
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/Transformers4Rec/transformers4rec/torch/trainer.py", line 787, in forward
    return self.module(inputs, *args)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/Transformers4Rec/transformers4rec/torch/model/base.py", line 522, in forward
    outputs.update(head(inputs, call_body=True, training=training, always_output_dict=True))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/Transformers4Rec/transformers4rec/torch/model/base.py", line 388, in forward
    body_outputs = self.body(body_outputs, training=training)
  File "/workspace/Transformers4Rec/transformers4rec/config/schema.py", line 50, in __call__
    return super().__call__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/Transformers4Rec/transformers4rec/torch/block/base.py", line 148, in forward
    input = module(input, **filtered_kwargs)
  File "/workspace/Transformers4Rec/transformers4rec/config/schema.py", line 50, in __call__
    return super().__call__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/Transformers4Rec/transformers4rec/torch/block/transformer.py", line 178, in forward
    model_outputs = self.transformer(**filtered_transformer_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/albert/modeling_albert.py", line 708, in forward
    buffered_token_type_ids = self.embeddings.token_type_ids[:, :seq_length]
UnboundLocalError: local variable 'seq_length' referenced before assignment
```

This error pops up with Transformers==4.92 version and does not occur with transformers==**4.11.3**. So, it'd be better upgrade the transformers version in the requirements file to `4.11.3`

### Steps/Code to reproduce bug
run the following code with the processed g1_news dataset.

```
DATA_PATH=/g1news/
FEATURE_SCHEMA_PATH=./datasets_configs/ecom_rees46/rees46_schema.pbtxt
CUDA_VISIBLE_DEVICES=0 python3 -m t4r_paper_repro.transf_exp_main --output_dir ./tmp/ --overwrite_output_dir --do_train --do_eval --validate_every 10 --logging_steps 20 --save_steps 0 --data_path $DATA_PATH --features_schema_path $FEATURE_SCHEMA_PATH --fp16 --data_loader_engine nvtabular --start_time_window_index 1 --final_time_window_index 380 --time_window_folder_pad_digits 4 --model_type albert --loss_type cross_entropy --per_device_eval_batch_size 512 --similarity_type concat_mlp --tf_out_activation tanh --inp_merge mlp --learning_rate_warmup_steps 0 --learning_rate_schedule linear_with_warmup --hidden_act gelu --num_train_epochs 10 --compute_metrics_each_n_steps 1 --session_seq_length_max 20 --eval_on_last_item_seq_only --mf_constrained_embeddings --layer_norm_featurewise --mlm --num_hidden_groups -1 --inner_group_num 1 --per_device_train_batch_size 128 --learning_rate 0.00018961089951392257 --dropout 0.0 --input_dropout 0.2 --weight_decay 1.6325081940093224e-05 --d_model 384 --item_embedding_dim 384 --n_layer 4 --n_head 2 --label_smoothing 0.7000000000000001 --stochastic_shared_embeddings_replacement_prob 0.06 --item_id_embeddings_init_std 0.15 --other_embeddings_init_std 0.01 --mlm_probability 0.2 --eval_on_test_set --seed 100
```

### Expected behavior

The training and eval should work without any issue.

### Environment details
`merlin-training-pytorch:21.09` docker image

**Comment by sararb** [comment]
This is related to open task #262. The [WIP] open PR #290 is fixing the issue by upgrading the HF version to 4.11.*.
