### ISSUE TITLE
[BUG] OOM issues when reproducing the some of the experiments from the Transformers4Rec paper with the new PyTorch API

### ISSUE THREAD

**Issue by gabrielspmoreira** [NVIDIA-Merlin/Transformers4Rec#322]
### Bug description
The experiments reported in the [Transformers4Rec paper](https://github.com/NVIDIA-Merlin/publications/blob/main/2021_acm_recsys_transformers4rec/recsys21_transformers4rec_paper.pdf) (published at ACM RecSys'21) were performed using an earlier (pre-release) version of the library, which was later refactored for public release, as described [here](https://github.com/NVIDIA-Merlin/publications/blob/main/2021_acm_recsys_transformers4rec/experiments_reproducibility_commands.md).
Some of the experiments that ran successfully before in a V100 32GB GPU now raise an Out-Of-Memory (OOM) error with the same hardware with the refactored PyTorch API.
This bug is for investigating the cause of OOM issues for those experiments

### Steps/Code to reproduce bug

1. Setup a docker container with the latest Merlin for PyTorch Training (21.11)
```bash
REES46_ECOM_DATASET_PATH=/path/to/dataset
docker run --rm --gpus all -it -v $REES46_ECOM_DATASET_PATH:/ecomrees nvcr.io/nvidia/merlin/merlin-pytorch-training:21.11
```

2. Within the container, pull the latest Transformers4Rec code and install requirements
```bash
cd /transformers4rec/ && git pull origin main && pip install -e .
pip install -r /transformers4rec/examples/t4rec_paper_experiments/requirements.txt
cd /transformers4rec/examples/t4rec_paper_experiments/
```

3. Run an experiment with Transformer-XL
```bash
CUDA_VISIBLE_DEVICES=0 python3 -m t4r_paper_repro.transf_exp_main --output_dir ./tmp_transfoxl/ --overwrite_output_dir --do_train --do_eval --data_path /home/gmoreira/dataset/ecommerce_dataset/ecommerce_preproc_v5_with_repetitions_day_folders --data_loader_engine nvtabular --validate_every 10 --logging_steps 20 --save_steps 0 --experiments_group local_test  --features_schema_path datasets_configs/ecom_rees46/rees46_schema.pbtxt --fp16 --data_loader_engine nvtabular --start_time_window_index 1 --final_time_window_index 30 --time_window_folder_pad_digits 4 --model_type transfoxl --loss_type cross_entropy --per_device_eval_batch_size 512 --similarity_type concat_mlp --tf_out_activation tanh --inp_merge mlp --learning_rate_warmup_steps 0 --learning_rate_schedule linear_with_warmup --hidden_act gelu --num_train_epochs 10 --dataloader_drop_last --compute_metrics_each_n_steps 1 --session_seq_length_max 20 --eval_on_last_item_seq_only --mf_constrained_embeddings --layer_norm_featurewise --per_device_train_batch_size 512 --learning_rate 0.001007765821083962 --dropout 0.1 --input_dropout 0.30000000000000004 --weight_decay 1.0673054163921092e-06 --d_model 448 --item_embedding_dim 320 --n_layer 1 --n_head 1 --label_smoothing 0.2 --stochastic_shared_embeddings_replacement_prob 0.02 --item_id_embeddings_init_std 0.15 --other_embeddings_init_std 0.01 --eval_on_test_set --seed 500
```

4. The experiment uses incremental training and evaluation, training only data of one day and evaluating on the next day. That script will raise the following OOM error when training on day 18 (after about 3h 11m 54s)

```
Traceback (most recent call last):
  File "/home/gmoreira/miniconda3/envs/transf4rec_hf4.6.0_nvt0.6_cuda11.0/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gmoreira/miniconda3/envs/transf4rec_hf4.6.0_nvt0.6_cuda11.0/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gmoreira/projects/nvidia/nvidia_merlin/Transformers4Rec/examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py", line 394, in <module>
    main()
  File "/home/gmoreira/projects/nvidia/nvidia_merlin/Transformers4Rec/examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py", line 163, in main
    results_over_time = incremental_train_eval(
  File "/home/gmoreira/projects/nvidia/nvidia_merlin/Transformers4Rec/examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py", line 239, in incremental_train_eval
    train_metrics = trainer.evaluate(metric_key_prefix="train")
  File "/home/gmoreira/miniconda3/envs/transf4rec_hf4.6.0_nvt0.6_cuda11.0/lib/python3.8/site-packages/transformers/trainer.py", line 2037, in evaluate
    eval_dataloader = self.get_eval_dataloader(eval_dataset)
  File "/home/gmoreira/projects/nvidia/nvidia_merlin/Transformers4Rec/transformers4rec/torch/trainer.py", line 167, in get_eval_dataloader
    return T4RecDataLoader.parse(self.args.data_loader_engine).from_schema(
  File "/home/gmoreira/projects/nvidia/nvidia_merlin/Transformers4Rec/transformers4rec/torch/utils/data_utils.py", line 310, in from_schema
    nvt_loader = cls(
  File "/home/gmoreira/projects/nvidia/nvidia_merlin/Transformers4Rec/transformers4rec/torch/utils/data_utils.py", line 227, in __init__
    self.set_dataset(buffer_size, engine, reader_kwargs)
  File "/home/gmoreira/projects/nvidia/nvidia_merlin/Transformers4Rec/transformers4rec/torch/utils/data_utils.py", line 258, in set_dataset
    dataset = validate_dataset(
  File "/home/gmoreira/projects/nvidia/nvidia_merlin/Transformers4Rec/merlin_standard_lib/utils/misc_utils.py", line 239, in validate_dataset
    return Dataset(files, engine=engine, **reader_kwargs)
  File "/home/gmoreira/projects/nvidia/NVTabular/nvtabular/io/dataset.py", line 285, in __init__
    self.engine = ParquetDatasetEngine(
  File "/home/gmoreira/projects/nvidia/NVTabular/nvtabular/io/parquet.py", line 86, in __init__
    rg_byte_size_0 = _memory_usage(cudf.io.read_parquet(path0, row_groups=0))
  File "/home/gmoreira/miniconda3/envs/transf4rec_hf4.6.0_nvt0.6_cuda11.0/lib/python3.8/site-packages/cudf/io/parquet.py", line 250, in read_parquet
    return libparquet.read_parquet(
  File "cudf/_lib/parquet.pyx", line 110, in cudf._lib.parquet.read_parquet
  File "cudf/_lib/parquet.pyx", line 160, in cudf._lib.parquet.read_parquet
MemoryError: std::bad_alloc: CUDA error at: /home/gmoreira/miniconda3/envs/transf4rec_hf4.6.0_nvt0.6_cuda11.0/include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorMemoryAllocation out of memory
```

### Expected behavior
The experiment should finish without OOM errors

### Environment details
**Latest Merlin for PyTorch Training (21.11) - nvcr.io/nvidia/merlin/merlin-pytorch-training:21.11**
- Transformers4Rec version: 0.1.0
- transformers: 4.12.3
- Platform: Ubuntu 20.04
- Python version: 3.8.12
- Huggingface Transformers version: 1.12
- PyTorch version: 1.10
- V100 GPU 32 GB

**Comment by gabrielspmoreira** [comment]
Have ran in the 2nd GPU of my workstation and it completed successfully. That probably happened because my 1st GPU has some memory reserved for display graphics and as the hyperparameters for the experiment emerged from a hypertuning process with 100 trials, the best hyperparameters to to use the maximum possible GPU memory to allow for larger models and batch sizes. Closing this issue.
