### ISSUE TITLE
[BUG] nvtabular never registered with registry torch.dataloader_loader

### ISSUE THREAD

**Issue by farrokhsiar** [NVIDIA-Merlin/Transformers4Rec#461]
### Bug description

As I go through one one the examples, on end to end online session, I face the error below: 

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/xxx/Documents/Transformers4Rec/examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.py", line 152, in <module>
    OT_results = fit_and_evaluate(recsys_trainer, start_time_index=178, end_time_index=180, input_dir='./preproc_sessions_by_day')
  File "/Users/xxx/Documents/Transformers4Rec/transformers4rec/torch/utils/examples_utils.py", line 77, in fit_and_evaluate
    trainer.train()
  File "/Users/xxx/.local/share/virtualenvs/Transformers4Rec-6fqVuXJJ/lib/python3.9/site-packages/transformers/trainer.py", line 1203, in train
    train_dataloader = self.get_train_dataloader()
  File "/Users/xxx/Documents/Transformers4Rec/transformers4rec/torch/trainer.py", line 147, in get_train_dataloader
    return T4RecDataLoader.parse(self.args.data_loader_engine).from_schema(
  File "/Users/xxx/Documents/Transformers4Rec/transformers4rec/torch/utils/data_utils.py", line 53, in parse
    return dataloader_registry.parse(class_or_str)
  File "/Users/xxx/Documents/Transformers4Rec/merlin_standard_lib/registry.py", line 265, in parse
    return self[class_or_str]
  File "/Users/xxx/Documents/Transformers4Rec/merlin_standard_lib/registry.py", line 232, in __getitem__
    raise KeyError(
KeyError: 'nvtabular never registered with registry torch.dataloader_loader. Available:\n     pyarrow:\n      * pyarrow\n      * pyarrow_builder'
```

### Environment details

The environment can be found here:
python_version = "3.8"
```
merlin==1.8.5
  - cached-property [required: Any, installed: 1.5.2]
  - celery [required: >=5.0.3, installed: 5.2.7]
    - billiard [required: >=3.6.4.0,<4.0, installed: 3.6.4.0]
    - click [required: >=8.0.3,<9.0, installed: 8.1.3]
    - click-didyoumean [required: >=0.0.3, installed: 0.3.0]
      - click [required: >=7, installed: 8.1.3]
    - click-plugins [required: >=1.1.1, installed: 1.1.1]
      - click [required: >=4.0, installed: 8.1.3]
    - click-repl [required: >=0.2.0, installed: 0.2.0]
      - click [required: Any, installed: 8.1.3]
      - prompt-toolkit [required: Any, installed: 3.0.30]
        - wcwidth [required: Any, installed: 0.2.5]
      - six [required: Any, installed: 1.16.0]
    - kombu [required: >=5.2.3,<6.0, installed: 5.2.4]
      - amqp [required: >=5.0.9,<6.0.0, installed: 5.1.1]
        - vine [required: >=5.0.0, installed: 5.0.0]
      - vine [required: Any, installed: 5.0.0]
    - pytz [required: >=2021.3, installed: 2022.1]
    - vine [required: >=5.0.0,<6.0, installed: 5.0.0]
  - coloredlogs [required: Any, installed: 15.0.1]
    - humanfriendly [required: >=9.1, installed: 10.0]
  - cryptography [required: Any, installed: 37.0.4]
    - cffi [required: >=1.12, installed: 1.15.1]
      - pycparser [required: Any, installed: 2.21]
  - maestrowf [required: ==1.1.7dev0, installed: 1.1.7.dev0]
    - filelock [required: Any, installed: 3.7.1]
    - PyYAML [required: >=4.2b1, installed: 6.0]
    - six [required: Any, installed: 1.16.0]
    - tabulate [required: Any, installed: 0.8.10]
  - numpy [required: Any, installed: 1.22.4]
  - parse [required: Any, installed: 1.19.0]
  - psutil [required: >=5.1.0, installed: 5.9.1]
  - pyyaml [required: >=5.1.2, installed: 6.0]
  - tabulate [required: Any, installed: 0.8.10]
nvtabular==1.3.3
  - merlin-core [required: >=0.2.0, installed: 0.5.0]
    - betterproto [required: <2.0.0, installed: 1.2.5]
      - grpclib [required: Any, installed: 0.4.2]
        - h2 [required: >=3.1.0,<5, installed: 4.1.0]
          - hpack [required: >=4.0,<5, installed: 4.0.0]
          - hyperframe [required: >=6.0,<7, installed: 6.0.1]
        - multidict [required: Any, installed: 6.0.2]
      - stringcase [required: Any, installed: 1.2.0]
    - dask [required: >=2021.11.2, installed: 2022.7.1]
      - cloudpickle [required: >=1.1.1, installed: 2.1.0]
      - fsspec [required: >=0.6.0, installed: 2022.5.0]
      - packaging [required: >=20.0, installed: 21.3]
        - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
      - partd [required: >=0.3.10, installed: 1.2.0]
        - locket [required: Any, installed: 1.0.0]
        - toolz [required: Any, installed: 0.12.0]
      - pyyaml [required: >=5.3.1, installed: 6.0]
      - toolz [required: >=0.8.2, installed: 0.12.0]
    - distributed [required: >=2021.11.2, installed: 2022.7.1]
      - click [required: >=6.6, installed: 8.1.3]
      - cloudpickle [required: >=1.5.0, installed: 2.1.0]
      - dask [required: ==2022.7.1, installed: 2022.7.1]
        - cloudpickle [required: >=1.1.1, installed: 2.1.0]
        - fsspec [required: >=0.6.0, installed: 2022.5.0]
        - packaging [required: >=20.0, installed: 21.3]
          - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
        - partd [required: >=0.3.10, installed: 1.2.0]
          - locket [required: Any, installed: 1.0.0]
          - toolz [required: Any, installed: 0.12.0]
        - pyyaml [required: >=5.3.1, installed: 6.0]
        - toolz [required: >=0.8.2, installed: 0.12.0]
      - jinja2 [required: Any, installed: 3.1.2]
        - MarkupSafe [required: >=2.0, installed: 2.1.1]
      - locket [required: >=1.0.0, installed: 1.0.0]
      - msgpack [required: >=0.6.0, installed: 1.0.4]
      - packaging [required: >=20.0, installed: 21.3]
        - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
      - psutil [required: >=5.0, installed: 5.9.1]
      - pyyaml [required: Any, installed: 6.0]
      - sortedcontainers [required: !=2.0.1,!=2.0.0, installed: 2.4.0]
      - tblib [required: >=1.6.0, installed: 1.7.0]
      - toolz [required: >=0.8.2, installed: 0.12.0]
      - tornado [required: >=6.0.3,<6.2, installed: 6.1]
      - urllib3 [required: Any, installed: 1.26.10]
      - zict [required: >=0.1.3, installed: 2.2.0]
        - heapdict [required: Any, installed: 1.0.1]
    - numba [required: >=0.54, installed: 0.55.2]
      - llvmlite [required: >=0.38.0rc1,<0.39, installed: 0.38.1]
      - numpy [required: >=1.18,<1.23, installed: 1.22.4]
      - setuptools [required: Any, installed: 63.2.0]
    - packaging [required: Any, installed: 21.3]
      - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
    - pandas [required: >=1.2.0,<1.4.0dev0, installed: 1.3.5]
      - numpy [required: >=1.20.0, installed: 1.22.4]
      - python-dateutil [required: >=2.7.3, installed: 2.8.2]
        - six [required: >=1.5, installed: 1.16.0]
      - pytz [required: >=2017.3, installed: 2022.1]
    - protobuf [required: >=3.0.0, installed: 3.20.1]
    - pyarrow [required: >=5.0.0, installed: 8.0.0]
      - numpy [required: >=1.16.6, installed: 1.22.4]
    - tensorflow-metadata [required: >=1.2.0, installed: 1.9.0]
      - absl-py [required: >=0.9,<2.0.0, installed: 1.2.0]
      - googleapis-common-protos [required: >=1.52.0,<2, installed: 1.56.4]
        - protobuf [required: >=3.15.0,<5.0.0dev, installed: 3.20.1]
      - protobuf [required: >=3.13,<4, installed: 3.20.1]
    - tqdm [required: >=4.0, installed: 4.64.0]
redis==4.3.4
  - async-timeout [required: >=4.0.2, installed: 4.0.2]
  - deprecated [required: >=1.2.3, installed: 1.2.13]
    - wrapt [required: >=1.10,<2, installed: 1.14.1]
  - packaging [required: >=20.4, installed: 21.3]
    - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
SQLAlchemy==1.4.39
torchmetrics==0.3.2
  - packaging [required: Any, installed: 21.3]
    - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
  - torch [required: >=1.3.1, installed: 1.12.0]
    - typing-extensions [required: Any, installed: 4.3.0]
transformers4rec==0.1.11+0.gd3c199ce.dirty
  - betterproto [required: <2.0.0, installed: 1.2.5]
    - grpclib [required: Any, installed: 0.4.2]
      - h2 [required: >=3.1.0,<5, installed: 4.1.0]
        - hpack [required: >=4.0,<5, installed: 4.0.0]
        - hyperframe [required: >=6.0,<7, installed: 6.0.1]
      - multidict [required: Any, installed: 6.0.2]
    - stringcase [required: Any, installed: 1.2.0]
  - numpy [required: >=1.17.0, installed: 1.22.4]
  - pyarrow [required: >=1.0, installed: 8.0.0]
    - numpy [required: >=1.16.6, installed: 1.22.4]
  - tqdm [required: >=4.27, installed: 4.64.0]
  - transformers [required: <4.19, installed: 4.18.0]
    - filelock [required: Any, installed: 3.7.1]
    - huggingface-hub [required: >=0.1.0,<1.0, installed: 0.8.1]
      - filelock [required: Any, installed: 3.7.1]
      - packaging [required: >=20.9, installed: 21.3]
        - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
      - pyyaml [required: >=5.1, installed: 6.0]
      - requests [required: Any, installed: 2.28.1]
        - certifi [required: >=2017.4.17, installed: 2022.6.15]
        - charset-normalizer [required: >=2,<3, installed: 2.1.0]
        - idna [required: >=2.5,<4, installed: 3.3]
        - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.10]
      - tqdm [required: Any, installed: 4.64.0]
      - typing-extensions [required: >=3.7.4.3, installed: 4.3.0]
    - numpy [required: >=1.17, installed: 1.22.4]
    - packaging [required: >=20.0, installed: 21.3]
      - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
    - pyyaml [required: >=5.1, installed: 6.0]
    - regex [required: !=2019.12.17, installed: 2022.7.9]
    - requests [required: Any, installed: 2.28.1]
      - certifi [required: >=2017.4.17, installed: 2022.6.15]
      - charset-normalizer [required: >=2,<3, installed: 2.1.0]
      - idna [required: >=2.5,<4, installed: 3.3]
      - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.10]
    - sacremoses [required: Any, installed: 0.0.53]
      - click [required: Any, installed: 8.1.3]
      - joblib [required: Any, installed: 1.1.0]
      - regex [required: Any, installed: 2022.7.9]
      - six [required: Any, installed: 1.16.0]
      - tqdm [required: Any, installed: 4.64.0]
    - tokenizers [required: >=0.11.1,<0.13,!=0.11.3, installed: 0.12.1]
    - tqdm [required: >=4.27, installed: 4.64.0]
```

**Comment by SalvadorMartiRoman** [comment]
If you are referring to [Getting Started: Session-based Recommendation with Synthetic Data](https://nvidia-merlin.github.io/Transformers4Rec/main/examples/getting-started-session-based/index.html#getting-started-session-based-recommendation-with-synthetic-data). Have you tried running the [notebook](https://nvidia-merlin.github.io/Transformers4Rec/main/examples/getting-started-session-based/01-ETL-with-NVTabular.html) where you create the synthetic data first?

I had a similar issue with the starting code when I didn't notice my execution of the first notebook was failing. In my case, the first notebook was failing because the Nvidia drivers in my environment didn't support Cuda 11.7.

**Comment by rnyak** [comment]
@farrokhsiar thanks for your interest in Transformers4Rec. We need more details:

- which example notebook is that?
-  which container do you use if you use a merlin docker container? if not, what env you run this example in?
- what's your cuda driver version, cuda version and cuda toolkit version? (run `nvidia-smi` and share the results here pls.)
-  do you have a GPU? what's your HW specs?

Thanks.

**Comment by farrokhsiar** [comment]
I am referring to the Transformers4Rec/examples/end-to-end-session-based. I have executed the first notebook on a machine with NVidia GPU. I could run the notebook successfully, and the I transfered the processed data to a Mac M1. I'm trying to run the modeling section on the Mac.

**Comment by rnyak** [comment]
`I'm trying to run the modeling section on the Mac.`

Does your Mac has Merlin libaries (i.e. Transformers4Rec and Nvtabular) installed? if yes how did you install them?

**Comment by rnyak** [comment]
what are your `transformers` and `pytorch` versions?  If you do not have a GPU on your Mac ( I assume you dont) you cannot train TRansformers4Rec model with NVTabular data loader engine, you need to train with pyarrow engine. because NVT engine requires a GPU.

to train with `pyarrow` engine on  CPU:

you have to set `data_loader_engine='pyarrow'`  and `no_cuda=True`  as in this unit test example: https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/tests/torch/test_trainer.py#L59-L75

**Comment by farrokhsiar** [comment]
Looks like setting `data_loader_engine='pyarrow'` and `no_cuda=True` solved the problem. 
Tahnks.
