### ISSUE TITLE
[QST] Multi-GPU training with DataParallel issue: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! 

### ISSUE THREAD

**Issue by harshit1742** [NVIDIA-Merlin/Transformers4Rec#494]
## Details

I am trying to train `NextItemPredictionTask` model using `transformers4rec==0.1.13` which has `DataParallel` method fixed.
Reference: Issue https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/483

I am following the notebook [Transformers4Rec/examples/tutorial](https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/tutorial/03-Session-based-recsys.ipynb), to train a next item click prediction model for my own dataset on sequence of items. 

Params which I've changed are: learning_rate=0.01, fp16=True, per_device_train_batch_size = 64, d_model=16, rest are as in the notebook. 

I get following error while training. 
```
Projecting inputs of NextItemPredictionTask to'64' As weight tying requires the input dimension '16' to be equal to the item-id embedding dimension '64'
Using amp fp16 backend
********************
Launch training for day 1 are:
********************

/opt/conda/lib/python3.8/site-packages/cudf/core/dataframe.py:1292: UserWarning: The deep parameter is ignored and is onlyincluded for pandas compatibility.
  warnings.warn(
***** Running training *****
  Num examples = 3605184
  Num Epochs = 3
  Instantaneous batch size per device = 64
  Total train batch size (w. parallel, distributed & accumulation) = 256
  Gradient Accumulation steps = 1
  Total optimization steps = 168993
  0%|                                                                                           | 0/168993 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main-multi-gpu.py", line 100, in <module>
    trainer.train()
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1316, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1847, in training_step
    loss = self.compute_loss(model, inputs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1881, in compute_loss
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 463, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/torch/trainer.py", line 826, in forward
    return self.wrapper_module(inputs, *args)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 463, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/torch/model/base.py", line 525, in forward
    head(inputs, call_body=True, training=training, always_output_dict=True, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/torch/model/base.py", line 390, in forward
    body_outputs = self.body(body_outputs, training=training, ignore_masking=ignore_masking)
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/config/schema.py", line 50, in __call__
    return super().__call__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/torch/block/base.py", line 152, in forward
    input = module(input, training=training, ignore_masking=ignore_masking)
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/config/schema.py", line 50, in __call__
    return super().__call__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/torch/tabular/base.py", line 390, in __call__
    outputs = super().__call__(inputs, *args, **kwargs)  # noqa
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/torch/features/sequence.py", line 251, in forward
    outputs = super(TabularSequenceFeatures, self).forward(inputs)
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/torch/tabular/base.py", line 602, in forward
    outputs.update(layer(inputs))
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/config/schema.py", line 50, in __call__
    return super().__call__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/torch/tabular/base.py", line 390, in __call__
    outputs = super().__call__(inputs, *args, **kwargs)  # noqa
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers4rec/torch/features/embedding.py", line 231, in forward
    embedded_outputs[name] = self.embedding_tables[name](val)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1111, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2148, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
```

This is the code snippet.
```
#!/usr/bin/env python
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0,1,2,3"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"
import glob
import torch 
torch.cuda.empty_cache()
import transformers4rec.torch as tr
from transformers4rec.torch.ranking_metric import NDCGAt, RecallAt
from merlin_standard_lib import Schema

# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Define schema object to pass it to the TabularSequenceFeatures class
SCHEMA_PATH = '/workspace/t4rec/schema_meesho.pb'
schema = Schema().from_proto_text(SCHEMA_PATH)

# Create a sub-schema only with the selected features
schema = schema.select_by_name(['catalog_code_seq'])

MAX_SEQ_LEN=20

#Input 
sequence_length, d_model = MAX_SEQ_LEN, 16
# Define input module to process tabular input-features and to prepare masked inputs
inputs= tr.TabularSequenceFeatures.from_schema(
    schema,
    max_sequence_length=sequence_length,
    d_output=d_model,
    masking="mlm",
)

# Define XLNetConfig class and set default parameters for HF XLNet config  
transformer_config = tr.XLNetConfig.build(
    d_model=d_model, n_head=4, n_layer=2, total_seq_length=sequence_length
)
# Define the model block including: inputs, masking, projection and transformer block.
body = tr.SequentialBlock(
    inputs, tr.MLPBlock([d_model]), tr.TransformerBlock(transformer_config, masking=inputs.masking)
)

# Define the head for to next item prediction task 
head = tr.Head(
    body,
    tr.NextItemPredictionTask(weight_tying=True, hf_format=True, 
                              metrics=[NDCGAt(top_ks=[10, 20], labels_onehot=True),  
                                       RecallAt(top_ks=[10, 20], labels_onehot=True)]),
)

# Get the end-to-end Model class 
model = tr.Model(head)
model = torch.nn.parallel.DataParallel(model)
# model.to(device)
# **Set training arguments**

from transformers4rec.config.trainer import T4RecTrainingArguments
from transformers4rec.torch import Trainer

#Set arguments for training 
training_args = T4RecTrainingArguments(
            output_dir="/workspace/t4rec/",
            max_sequence_length=MAX_SEQ_LEN,
            data_loader_engine='nvtabular',
            num_train_epochs=3, 
            dataloader_drop_last=False,
            per_device_train_batch_size = 64,
            per_device_eval_batch_size = 32,
            gradient_accumulation_steps = 1,
            learning_rate=0.01,
            report_to = [],
            logging_steps=200,
            fp16=True,
            save_steps=5000,
            overwrite_output_dir=True,
            save_strategy='epoch',
        )

# Instantiate the T4Rec Trainer, which manages training and evaluation
trainer = Trainer(
    model=model,
    args=training_args,
    schema=schema,
    compute_metrics=True,
)

OUTPUT_DIR = os.environ.get("OUTPUT_DIR", "/workspace/t4rec/data/")

start_time_window_index = 1
final_time_window_index = 4
for time_index in range(start_time_window_index, final_time_window_index):
    # Set data 
    time_index_train = time_index
    time_index_eval = time_index + 1
    train_paths = glob.glob(os.path.join(OUTPUT_DIR, f"{time_index_train}/train.parquet"))
    eval_paths = glob.glob(os.path.join(OUTPUT_DIR, f"{time_index_eval}/valid.parquet"))
    # Train on day related to time_index 
    print('*'*20)
    print("Launch training for day %s are:" %time_index)
    print('*'*20 + '\n')
    trainer.train_dataset_or_path = train_paths
    trainer.reset_lr_scheduler()
    trainer.train()
    trainer.state.global_step +=1
    # Evaluate on the following day
    trainer.eval_dataset_or_path = eval_paths
    train_metrics = trainer.evaluate(metric_key_prefix='eval')
    print('*'*20)
    print("Eval results for day %s are:\t" %time_index_eval)
    print('\n' + '*'*20 + '\n')
    for key in sorted(train_metrics.keys()):
        print(" %s = %s" % (key, str(train_metrics[key]))) 
    wipe_memory()


with open("/workspace/t4rec/results.txt", 'a') as f:
    f.write('\n')
    f.write('XLNet-MLM accuracy results:')
    f.write('\n')
    for key, value in  model.compute_metrics().items(): 
        f.write('%s:%s\n' % (key, value.item()))

```

When using t4rec trainer, should we add `model.to(device)`?

Does `transformers4rec` automatically copies data to GPU:0 via trainer and `nvTabular`?

**Comment by rnyak** [comment]
@harshit1742 can you tell us about your env? are you using docker image? if yes can you use the latest merlin PyTorch image? 

`docker pull nvcr.io/nvidia/merlin/merlin-pytorch:22.09`

Also please comment out `model = torch.nn.parallel.DataParallel(model)` line. This should be done under the hood after the recent changes we did in this [PR](https://github.com/NVIDIA-Merlin/Transformers4Rec/pull/483).

**Comment by harshit1742** [comment]
@rnyak I am using docker image `nvcr.io/nvidia/merlin/merlin-pytorch:22.09` on `ml.g4dn.12xlarge` aws sagemaker instance.

The model is training as you suggested but it is taking longer than **non** **DataParallel** case. 

Attaching screenshot of model training. It shows 90+ hours to train 1 epoc with batch-size per gpu : `64`. Can you suggest what changes I need to make for it to be faster?


<img width="1114" alt="multi-gpu-training" src="https://user-images.githubusercontent.com/108255636/193762824-54e5919d-1d41-4d8f-9459-e043b72b9389.png">

**Comment by harshit1742** [comment]
@rnyak It only takes 10 hours to train same model on CPU without `DataParallel`. Why is it that `DataParallel` taking so long?

**Comment by rnyak** [comment]
@harshit1742 how long does it take to train on a single GPU? can you only use single GPU? via

`os.environ["CUDA_VISIBLE_DEVICES"]="0"`
 
Do you have a very large model or very large dataset?

**Comment by harshit1742** [comment]
With single GPU, I get CUDA Out of Memory error with batch size of 64.
<img width="1020" alt="batch-size-32-single-gpu" src="https://user-images.githubusercontent.com/108255636/193983419-324e0424-99c5-44f6-8be4-126329d8f9cf.png">

<br>
When batch-size reduced to 32, I get out of memory error after 368 steps. You can also see how long it will take to train one epoc.
<img width="1142" alt="batch-size-64-single-gpu" src="https://user-images.githubusercontent.com/108255636/193983407-86f5c21e-9121-4e05-b654-217d504b8e18.png">

When trained on CPU. I set `data_loader_engine="nvtabular"`. I did not set `no_cuda=True` parameter.  The code snippet is exactly the same for CPU training as with GPU training. I only added `os.environ["CUDA_VISIBLE_DEVICES"]="0,1,2,3"` when training with GPU.

**Comment by rnyak** [comment]
The recommended way to use `nvtabular` engine is with GPU.  Please use `data_loader_engine="pyarrow"` and set `no_cuda=True` if you want to train on CPU. 

we have a PR for Data parallel training that will be merged soon and it should address the longer training time you see on multiple-GPUs. 

for your OOM issue, what's your `max_seq` length?  what's the item_id cardinality in your schema file? you said  you are using your own dataset on sequence of items. what's the row_group memory size of each parquet file, and number of partitions in each parquet file and number of row groups in each parquet file?

**Comment by rnyak** [comment]
@harshit1742 can you please pull the latest main branch, and test again? you can do via:

`
git checkout main && git pull origin main && pip install . 
`

**Comment by rnyak** [comment]
closing due to no recent activity.
