### ISSUE TITLE
[BUG] mutli-gpu example is broken when we pull the release-22.11 branch of NVTabular

### ISSUE THREAD

**Issue by rnyak** [NVIDIA-Merlin/Transformers4Rec#526]
### Bug description

I get the following error when I run the multi-gpu notebook example [03-Session-based-Yoochoose-multigpu-training-PyT.ipynb](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/end-to-end-session-based/03-Session-based-Yoochoose-multigpu-training-PyT.ipynb)

```
/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
/usr/local/lib/python3.8/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (NDCGAt). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_full_state_property`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.
                
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.8/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (DCGAt). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_full_state_property`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.
                
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.8/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (AvgPrecisionAt). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_full_state_property`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.
                
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.8/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (PrecisionAt). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_full_state_property`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.
                
  warnings.warn(*args, **kwargs)
/usr/local/lib/python3.8/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (RecallAt). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_full_state_property`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.
                
  warnings.warn(*args, **kwargs)
Projecting inputs of NextItemPredictionTask to'64' As weight tying requires the input dimension '320' to be equal to the item-id embedding dimension '64'
Projecting inputs of NextItemPredictionTask to'64' As weight tying requires the input dimension '320' to be equal to the item-id embedding dimension '64'
['./preproc_sessions_by_day/178/train.parquet']
********************
Launch training for day 178 are:
********************

UserWarning: User is advised to repartition the parquet file before training so npartitions>=global_size. Cudf or pandas can be used for repartitioning e.g.: df.to_parquet('file.parquet', row_group_size=N_ROWS/NPARTITIONS, engine='pyarrow') as npartitions=nr_rows/row_group_size.
['./preproc_sessions_by_day/178/train.parquet']
********************
Launch training for day 178 are:
********************

UserWarning: User is advised to repartition the parquet file before training so npartitions>=global_size. Cudf or pandas can be used for repartitioning e.g.: df.to_parquet('file.parquet', row_group_size=N_ROWS/NPARTITIONS, engine='pyarrow') as npartitions=nr_rows/row_group_size.
***** Running training *****
  Num examples = 14592
  Num Epochs = 10
  Instantaneous batch size per device = 384
  Total train batch size (w. parallel, distributed & accumulation) = 768
  Gradient Accumulation steps = 1
  Total optimization steps = 380
  0%|                                                   | 0/380 [00:00<?, ?it/s]Traceback (most recent call last):
  File "pyt_trainer.py", line 99, in <module>
    recsys_trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1290, in train
    for step, inputs in enumerate(epoch_iterator):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 668, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 706, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/usr/local/lib/python3.8/dist-packages/merlin/loader/loader_base.py", line 243, in __next__
    return self._get_next_batch()
  File "/usr/local/lib/python3.8/dist-packages/merlin/loader/loader_base.py", line 278, in _get_next_batch
    batch = next(self._batch_itr)
  File "/usr/local/lib/python3.8/dist-packages/merlin/loader/loader_base.py", line 402, in <genexpr>
    return (self._handle_tensors(batch) for batch in batches)
  File "/usr/local/lib/python3.8/dist-packages/nvtx/nvtx.py", line 101, in inner
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/loader/loader_base.py", line 546, in _handle_tensors
    X[column_name] = self._to_sparse_tensor(X[column_name], column_name)
  File "/usr/local/lib/python3.8/dist-packages/merlin/loader/loader_base.py", line 421, in _to_sparse_tensor
    values, offsets, diff_offsets, num_rows = self._pull_values_offsets(values_offset)
  File "/usr/local/lib/python3.8/dist-packages/merlin/loader/torch.py", line 139, in _pull_values_offsets
    offsets = torch.cat([offsets, torch.cuda.LongTensor([len(values)])])
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_cat)
/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/scatter_gather.py:9: UserWarning: is_namedtuple is deprecated, please use the python checks instead
  warnings.warn("is_namedtuple is deprecated, please use the python checks instead")
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1156 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 1157) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
pyt_trainer.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-09_20:28:11
  host      : fd1f978968a9
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1157)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

### Steps/Code to reproduce bug

1. you can use `merlin-pytorch:22.10` container and then pull the `22.11` branch of `NVTabular` and `Transformersrec` libraries.
2. Install the yoochoose click.dat data set
3. Run  ETL  [01-ETL-with-NVTabular.ipynb](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/end-to-end-session-based/01-ETL-with-NVTabular.ipynb) notebook first
4. Run the multi-gpu [03-Session-based-Yoochoose-multigpu-training-PyT.ipynb](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/end-to-end-session-based/03-Session-based-Yoochoose-multigpu-training-PyT.ipynb) nb.

THE ERROR OCCURS DUE TO RECENT CHANGES IN THE DATALOADER.

**Comment by nzarif** [comment]
Hi,
To add more details to this bug report:
A [commit](https://github.com/NVIDIA-Merlin/dataloader/commit/b6f9a67b2c0caf1b0b1ded10e5491b5a0f13230a) merged just recently has made modifications to the dataloader in core library. These changes lead to an error while calling `torch.cat()` for concating offsets on [this line](https://github.com/NVIDIA-Merlin/dataloader/blob/b6f9a67b2c0caf1b0b1ded10e5491b5a0f13230a/merlin/loader/torch.py#L138).
The error we see is:
` File "/usr/local/lib/python3.8/dist-packages/merlin/loader/torch.py", line 139, in _pull_values_offsets
    offsets = torch.cat([offsets, torch.cuda.LongTensor([len(values)])])
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_cat)`

When we see this error? While we are training a model using `DistributedDataParallel` mode. In this mode the dataloader on each step generates a separate batch for each GPU/worker. This means the `*input` of each GPU during forward pass will be a `Tensor` placed on the same GPU. `torch.cat()` is unable to concat Tensor that are placed on different GPUs so when we are using `DistributedDataParallel` mode we see the error.

Potential fix to this can be:
1. Using `Tensor.to()` to either send both tensors to same device for concating (probably is not the best idea)
2. Adding checks before calling `torch.cat()` and only concating tensors placed on the same device.
Correctness of either of these options depends on the logical way of concating in case of n_gpus>1.

**Comment by edknv** [comment]
@rnyak @nzarif I manually verified that the PR works with the notebook. Can you also verify on your end?

**Comment by edknv** [comment]
Once we verify the fix works, we can cherry-pick it onto the release branch.

**Comment by nzarif** [comment]
I checked latest version of dataloader on the main branch and it works okay with T4Rec multi-gpu training.

**Comment by edknv** [comment]
I cherry-picked the bug fix on to the `release-22.11` branch of merlin-dataloader: https://github.com/NVIDIA-Merlin/dataloader/commit/680f4444b843b8138b663a1ab2df2b48a0b94510
