### ISSUE TITLE
[QST] Paper - Experiments reproducibility - training error

### ISSUE THREAD

**Issue by nicoladisabato** [NVIDIA-Merlin/Transformers4Rec#630]
# ❓ Questions & Help

## Details

Hi, I'm trying to reproduce some results in the paper  (xlnet and bert) following this guide: https://github.com/NVIDIA-Merlin/Transformers4Rec/tree/main/examples/t4rec_paper_experiments

I literally followed the guide using google colab with gpu.

I've done these steps:

- git of the repo `https://github.com/NVIDIA-Merlin/Transformers4Rec.git`
- install `!pip install transformers4rec[pytorch,nvtabular]`
- install `!pip install -r requirements.txt` (using this: https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/t4rec_paper_experiments/requirements.txt)
- install and login with wandb
- `cd /content/Transformers4Rec/examples/t4rec_paper_experiments/t4r_paper_repro` 

I downloaded this ready-to-use [dataset](https://drive.google.com/file/d/1BvCHc4eXComuNK93bKhRM6cbg9y5p350/view?usp=share_link) 
I used the [schema](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/examples/t4rec_paper_experiments/datasets_configs/ecom_rees46/rees46_schema.pbtxt) file in the repo

when I run:

```
DATA_PATH=~/transformers4rec_paper_preproc_datasets/ecom_rees46/
FEATURE_SCHEMA_PATH=datasets_configs/ecom_rees46/rees46_schema.pbtxt
CUDA_VISIBLE_DEVICES=0 python3 -m transf_exp_main --output_dir ./tmp/ --overwrite_output_dir --do_train --do_eval --validate_every 10 --logging_steps 20 --save_steps 0 --data_path $DATA_PATH --features_schema_path $FEATURE_SCHEMA_PATH --fp16 --data_loader_engine merlin --start_time_window_index 1 --final_time_window_index 30 --time_window_folder_pad_digits 4 --model_type xlnet --loss_type cross_entropy --per_device_eval_batch_size 512 --similarity_type concat_mlp --tf_out_activation tanh --inp_merge mlp --learning_rate_warmup_steps 0 --learning_rate_schedule linear_with_warmup --hidden_act gelu --num_train_epochs 10 --dataloader_drop_last --compute_metrics_each_n_steps 1 --session_seq_length_max 20 --eval_on_last_item_seq_only --mf_constrained_embeddings --layer_norm_featurewise --attn_type bi --mlm --input_features_aggregation concat --per_device_train_batch_size 256 --learning_rate 0.00020171456712823088 --dropout 0.0 --input_dropout 0.0 --weight_decay 2.747484129693843e-05 --d_model 448 --item_embedding_dim 448 --n_layer 2 --n_head 8 --label_smoothing 0.5 --stochastic_shared_embeddings_replacement_prob 0.0 --item_id_embeddings_init_std 0.09 --other_embeddings_init_std 0.015 --mlm_probability 0.1 --embedding_dim_from_cardinality_multiplier 3.0 --eval_on_test_set --seed 100 --use_side_information_features
```

i have this error: 

```
***** Launch training for day 1: *****
/usr/local/lib/python3.8/dist-packages/merlin/io/dataset.py:253: UserWarning: Initializing an NVTabular Dataset in CPU mode.This is an experimental feature with extremely limited support!
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/content/Transformers4Rec/examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py", line 452, in <module>
    main()
  File "/content/Transformers4Rec/examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py", line 164, in main
    results_over_time = incremental_train_eval(
  File "/content/Transformers4Rec/examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py", line 292, in incremental_train_eval
    trainer.train()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1203, in train
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/lib/python3.8/dist-packages/transformers4rec/torch/trainer.py", line 151, in get_train_dataloader
    return T4RecDataLoader.parse(self.args.data_loader_engine).from_schema(
  File "/usr/local/lib/python3.8/dist-packages/transformers4rec/torch/utils/data_utils.py", line 334, in from_schema
    loader = cls(
  File "/usr/local/lib/python3.8/dist-packages/transformers4rec/torch/utils/data_utils.py", line 246, in __init__
    self.set_dataset(buffer_size, engine, reader_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers4rec/torch/utils/data_utils.py", line 284, in set_dataset
    dataset = validate_dataset(
  File "/usr/local/lib/python3.8/dist-packages/merlin_standard_lib/utils/misc_utils.py", line 240, in validate_dataset
    return Dataset(files, engine=engine, **reader_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/io/dataset.py", line 348, in __init__
    self.infer_schema()
  File "/usr/local/lib/python3.8/dist-packages/merlin/io/dataset.py", line 1132, in infer_schema
    dtypes = self.sample_dtypes(n=n, annotate_lists=True)
  File "/usr/local/lib/python3.8/dist-packages/merlin/io/dataset.py", line 1159, in sample_dtypes
    annotated = {
  File "/usr/local/lib/python3.8/dist-packages/merlin/io/dataset.py", line 1161, in <dictcomp>
    "dtype": list_val_dtype(_real_meta[col]) or _real_meta[col].dtype,
  File "/usr/local/lib/python3.8/dist-packages/merlin/core/dispatch.py", line 293, in list_val_dtype
    return pd.core.dtypes.cast.infer_dtype_from(next(iter(pd.core.common.flatten(ser))))[0]
StopIteration
```

What could be the problem? Thanks in advance for the help.

**Comment by rnyak** [comment]
@nicoladisabato 
- did you already install cudf and dask_cudf? this should be done first.
-  did you install the proper torch for gpu? please test if you can run a simple code with torch so that your gpus are visible? 
 you can test via:
```
import torch
print(torch.backends.cudnn.enabled)
print(torch.cuda.is_available())
print(torch.cuda.current_device())
```
- can you please install the following libs and test again?

```
pip install merlin-core
pip install merlin-dataloader
```

thanks.

**Comment by rnyak** [comment]
@nicoladisabato hello. did you get his issue solved? did you see my msg above?

**Comment by rnyak** [comment]
I am closing this ticket due to no recent activity.
